version: "2.0"

# source : https://github.com/linuxserver/docker-mariadb
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Los_Angeles
    volumes:
      - ./app:/config
    ports:
      - 3400:3306
    restart: unless-stopped

  # source https://docs.docker.com/compose/gettingstarted/
  db_cli:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=baseball
    volumes:
      - ./app
    ports:
      - 3401:3306
