version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 5000:80
    networks:
      - mars-network
    depends_on:
      - mars_service
  mars_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: mars_service
    environment:
      PORT: "8080"
    restart: unless-stopped
    volumes:
      - "./flask_examples/mars_model.pkl:/app/mars_model.pkl"
    networks:
      mars-network:
        aliases:
          - mars-service

networks:
  mars-network:
