version: "3.9"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Los_Angeles
    volumes:
      - /Users/annakrause/bda602/src/bda_602/scripts/hw_06_files/app:/config
    ports:
      - 3311:3306
    restart: unless-stopped

  db_cli:
    build:
      context: .
      dockerfile: Dockerfile
    #    image: mysql:latest
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=baseball
    volumes:
      - /Users/annakrause/bda602/src/bda_602/scripts/hw_06_files/app
    ports:
      - 3312:3306
