
FROM python:3.6.9

ENV APP_HOME /app
WORKDIR $APP_HOME
ENV PYTHONPATH /

# Get necessary system packages
RUN apt-get update \
  && apt-get install --no-install-recommends --yes \
     build-essential \
     python3 \
     python3-pip \
     python3-dev \
  && rm -rf /var/lib/apt/lists/*

# Get necessary python libraries
COPY requirements.txt .
RUN pip3 install --compile --no-cache-dir -r requirements.txt

# Copy over code
COPY hw_06_prep.sql hw_06_prep.sql
COPY hw_06_main.py hw_06_main.py

# Create an unprivileged user
RUN useradd --system --user-group --shell /sbin/nologin services

Switch to the unprivileged user
USER services

# Run app
CMD gunicorn --bind :$PORT --timeout 500 --workers 1 --threads 2 hw_06_files.hw_06_prep.sql
# CMD gunicorn --bind :$PORT --timeout 500 --workers 1 --threads 2 hw_06_files.hw_06_prep:hw_06_main.py
# CMD [ "gunicorn" , "--bind", ":$PORT", "--timeout 500", "--workers 1", "--threads 2", "hw_06_files.hw_06_prep",
# "hw_06_files.hw_06_main.py"]

# source : https://medium.com/cranecloud/docker-django-and-gunicorn-61275f4ea14c